module.exports = [
    {
        id: "single1",
        pavadinimas: "Resident Evil 4",
        zanras: "Survival horror",
        leidejas: "Capcom",
        kaina: 60,
        foto: "https://image.api.playstation.com/vulcan/ap/rnd/202210/0706/EVWyZD63pahuh95eKloFaJuC.png",
        aprasymas: "Resident Evil 4 is a 2023 survival horror game developed and published by Capcom. It is a remake of the 2005 game Resident Evil 4. Players control the US agent Leon S. Kennedy, who must save Ashley Graham, the daughter of the United States president, from the mysterious Los Illuminados cult.",
        platformos: ["PS5", "PS4", "XBOX", "PC"],
    },
    {
        id: "single2",
        pavadinimas: "Elden Ring",
        zanras: "Action RPG",
        leidejas: "FromSoftware Inc.",
        kaina: 60,
        foto: "https://cdn.cloudflare.steamstatic.com/steam/apps/1245620/header.jpg?t=1683618443",
        aprasymas: "THE NEW FANTASY ACTION RPG. Rise, Tarnished, and be guided by grace to brandish the power of the Elden Ring and become an Elden Lord in the Lands Between.",
        platformos: ["PS5", "PC"],
    },
    {
        id: "single3",
        pavadinimas: "Red Dead Redemption 2",
        zanras: "Action Adventure",
        leidejas: "Rockstar games",
        kaina: 60,
        foto: "https://upload.wikimedia.org/wikipedia/en/4/44/Red_Dead_Redemption_II.jpg",
        aprasymas: "Winner of over 175 Game of the Year Awards and recipient of over 250 perfect scores, RDR2 is the epic tale of outlaw Arthur Morgan and the infamous Van der Linde gang, on the run across America at the dawn of the modern age. Also includes access to the shared living world of Red Dead Online.",
        platformos: ["PS5", "PS4", "XBOX", "PC"],
    },
    {
        id: "multi1",
        pavadinimas: "Apex Legends",
        zanras: "Battle royale",
        leidejas: "Respawn Entertaiment",
        kaina: "Free to play",
        foto: "https://cdn.cloudflare.steamstatic.com/steam/apps/1172470/capsule_616x353.jpg?t=1685123076",
        aprasymas: "Apex Legends is a free-to-play battle royale-hero shooter game developed by Respawn Entertainment and published by Electronic Arts. It was released for PlayStation 4, Windows, and Xbox One in February 2019, for Nintendo Switch in March 2021, and for PlayStation 5 and Xbox Series X/S in March 2022.",
        zaideju_skaicius: 100,
        platformos: ["PS5", "PS4", "Nintendo", "XBOX", "PC", "Android", "IOS"],
        crossplay: "True",
    },
    {
        id: "multi2",
        pavadinimas: "Albion online",
        zanras: "MMORPG",
        leidejas: "Sandbox interactive",
        kaina: "Free to play",
        foto: "https://cdn.cloudflare.steamstatic.com/steam/apps/761890/capsule_616x353.jpg?t=1683539410",
        aprasymas: "Albion Online is a free medieval fantasy MMORPG developed by Sandbox Interactive, a studio based in Berlin, Germany. Set in a medieval world, Albion Online is a medieval fantasy game based on the Arthurian legends, with militaristic strategy aspects to it.",
        zaideju_skaicius: 100.000,
        platformos: ["PC", "Android", "IOS"],
        crossplay: "True",
    },
    {
        id: "multi3",
        pavadinimas: "Valorant",
        zanras: "First person shooter",
        leidejas: "Riot Games",
        kaina: "Free to play",
        foto: "https://cdn.arstechnica.net/wp-content/uploads/2020/04/valorant-listing-800x450.jpg",
        aprasymas: "Riot Games presents VALORANT: a 5v5 character-based tactical FPS where precise gunplay meets unique agent abilities.",
        zaideju_skaicius: 10,
        platformos: ["PC"],
        crossplay: "False",
    },
    {
        id: "internet1",
        pavadinimas: "Krunker",
        zanras: "First person shooter",
        leidejas: "Yendis Entertainment",
        kaina: "Free to play",
        foto: "https://images.crazygames.com/games/krunker-io/cover-1591336739727.png?auto=format%2Ccompress&q=45&cs=strip&ch=DPR&w=1200&h=630&fit=crop",
        aprasymas: "Krunker is a popular first-person shooter game in which the players fall into a dark work, tasked with combating other gamers from all over the world.",
        nuoroda: "https://krunker.io/",
        narsykles: ["Google chrome", "Opera", "Microsoft Edge"],
    },
    {
        id: "internet2",
        pavadinimas: "Geoguessr",
        zanras: "Geography",
        leidejas: "Geoguessr",
        kaina: "Free to play",
        foto: "https://www.seriouslyfreshmedia.com/wp-content/uploads/2016/06/cherrymedia-cherrysauce-geoguessr-1.jpg",
        aprasymas: "GeoGuessr is a browser-based geography game in which players guess locations from Google Street View imagery. The game features multiple game modes, including singleplayer and multiplayer competitions.",
        nuoroda: "https://www.geoguessr.com/",
        narsykles: ["Google chrome", "Opera", "Microsoft Edge"],
    },
    {
        id: "internet3",
        pavadinimas: "Agar.io",
        zanras: "Battle royale",
        leidejas: "Matheus Valadares",
        kaina: "Free to play",
        foto: "https://play-lh.googleusercontent.com/ZRfghwQudJzza7Zb7k1tlc7aXd3WpnVb48AGg_kP-r84kiOcsLKpeM5goGkAQVT16P0=w526-h296-rw",
        aprasymas: "Agario is unblocked private server where players can play through their browser. Agar.io is a funny game, this mode called pvp.",
        nuoroda: "https://agar.io/?#ffa",
        narsykles: ["Google chrome", "Opera", "Microsoft Edge"],
    },
    {
        id: "mobil1",
        pavadinimas: "Clash royale",
        zanras: "Strategy",
        leidejas: "Supercell",
        kaina: "Free to play",
        foto: "https://clashroyale.com/uploaded-images-blog/CR_facebook_share_02_180403_175322.jpg?mtime=20180403175322",
        aprasymas: "Clash Royale is a free-to-play real-time strategy video game developed and published by Supercell. The game combines elements from collectible card games, tower defense, and multiplayer online battle arena. The game was released globally on March 2, 2016.",
        os: ["Android", "IOS"],
        nuorodos: ["https://play.google.com/store/apps/details?id=com.supercell.clashroyale&hl=en_US", "https://apps.apple.com/us/app/clash-royale/id1053012308"],
    },
    {
        id: "mobil2",
        pavadinimas: "Clash of clans",
        zanras: "Strategy",
        leidejas: "Supercell",
        kaina: "Free to play",
        foto: "https://www.washingtonpost.com/rf/image_960w/2010-2019/WashingtonPost/2015/02/02/Others/Images/2015-02-02/coc_titlescreen_1400px1422902890.jpg",
        aprasymas: "Clash of Clans is a 2012 free-to-play mobile strategy video game developed and published by Finnish game developer Supercell. The game was released for iOS platforms on August 2, 2012, and on Google Play for Android on October 7, 2013.",
        os: ["Android", "IOS"],
        nuorodos: ["https://play.google.com/store/apps/details?id=com.supercell.clashofclans&hl=en_US", "https://apps.apple.com/us/app/clash-of-clans/id529479190"],
    },
    {
        id: "mobil3",
        pavadinimas: "Brawl stars",
        zanras: "Third person shooter",
        leidejas: "supercell",
        kaina: "Free to play",
        foto: "https://supercell.com/_next/static/media/games_thumbnail_brawlstars.5cd76330.jpg",
        aprasymas: "Brawl Stars is a multiplayer online battle arena and third-person hero shooter video game developed and published by the Finnish video game company Supercell. It was released worldwide on December 12, 2018, on iOS and Android. The game features various game modes, each with a different objective.",
        os: ["Android", "IOS"],
        nuorodos: ["https://play.google.com/store/apps/details?id=com.supercell.brawlstars&hl=en_US", "https://apps.apple.com/us/app/brawl-stars/id1229016807"],
    },
]